"""empty message

Revision ID: 9d507099705f
Revises: 
Create Date: 2024-05-27 21:03:17.752428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d507099705f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playlists_title', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('ix_songs_title', table_name='songs')
    op.drop_table('songs')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='users_playlist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('songs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='songs_playlist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='songs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_songs_title', 'songs', ['title'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('song_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='playlists_owner_id_fkey'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name='playlists_song_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='playlists_pkey')
    )
    op.create_index('ix_playlists_title', 'playlists', ['title'], unique=True)
    # ### end Alembic commands ###
